// FileName: riskyPyModuleNames.ts

// Keep this file synchronized with:
// - src/riskyPyModuleNames.ts
// - webview-ui/src/riskyPyModuleNames.ts

// Windows file systems are usually case-insensitive, so compare risky module names in lower case.

const SET_RESERVED_PACKAGE_NAMES = new Set<string>(
  ["liberrpa"].map((name) => name.toLowerCase())
);

const SET_LIBERRPA_EXPORTED_NAMES = new Set<string>(
  [
    "Mouse",
    "Keyboard",
    "Window",
    "UiInterface",
    "Browser",
    "Excel",
    "Outlook",
    "Application",
    "Database",
    "Data",
    "Str",
    "List",
    "Dict",
    "Regex",
    "Math",
    "Time",
    "File",
    "OCR",
    "Web",
    "Mail",
    "FTP",
    "Clipboard",
    "System",
    "Credential",
    "ScreenPrint",
    "Dialog",
    "Trigger",

    "Log",
    "delay",
    "get_component_resource_path",
    "PrjArgs",
    "CustomArgs",
    "DatabaseConnection",
  ].map((name) => name.toLowerCase())
);

const SET_PYTHON_STDLIB_MODULE_NAMES = new Set<string>(
  // Python 3.13 top-level standard library module names.
  [
    "__future__",
    "_abc",
    "_aix_support",
    "_android_support",
    "_apple_support",
    "_ast",
    "_asyncio",
    "_bisect",
    "_blake2",
    "_bz2",
    "_codecs",
    "_codecs_cn",
    "_codecs_hk",
    "_codecs_iso2022",
    "_codecs_jp",
    "_codecs_kr",
    "_codecs_tw",
    "_collections",
    "_collections_abc",
    "_colorize",
    "_compat_pickle",
    "_compression",
    "_contextvars",
    "_csv",
    "_ctypes",
    "_curses",
    "_curses_panel",
    "_datetime",
    "_dbm",
    "_decimal",
    "_elementtree",
    "_frozen_importlib",
    "_frozen_importlib_external",
    "_functools",
    "_gdbm",
    "_hashlib",
    "_heapq",
    "_imp",
    "_interpchannels",
    "_interpqueues",
    "_interpreters",
    "_io",
    "_ios_support",
    "_json",
    "_locale",
    "_lsprof",
    "_lzma",
    "_markupbase",
    "_md5",
    "_multibytecodec",
    "_multiprocessing",
    "_opcode",
    "_opcode_metadata",
    "_operator",
    "_osx_support",
    "_overlapped",
    "_pickle",
    "_posixshmem",
    "_posixsubprocess",
    "_py_abc",
    "_pydatetime",
    "_pydecimal",
    "_pyio",
    "_pylong",
    "_pyrepl",
    "_queue",
    "_random",
    "_scproxy",
    "_sha1",
    "_sha2",
    "_sha3",
    "_signal",
    "_sitebuiltins",
    "_socket",
    "_sqlite3",
    "_sre",
    "_ssl",
    "_stat",
    "_statistics",
    "_string",
    "_strptime",
    "_struct",
    "_suggestions",
    "_symtable",
    "_sysconfig",
    "_thread",
    "_threading_local",
    "_tkinter",
    "_tokenize",
    "_tracemalloc",
    "_typing",
    "_uuid",
    "_warnings",
    "_weakref",
    "_weakrefset",
    "_winapi",
    "_wmi",
    "_zoneinfo",
    "abc",
    "antigravity",
    "argparse",
    "array",
    "ast",
    "asyncio",
    "atexit",
    "base64",
    "bdb",
    "binascii",
    "bisect",
    "builtins",
    "bz2",
    "calendar",
    "cmath",
    "cmd",
    "code",
    "codecs",
    "codeop",
    "collections",
    "colorsys",
    "compileall",
    "concurrent",
    "configparser",
    "contextlib",
    "contextvars",
    "copy",
    "copyreg",
    "cProfile",
    "csv",
    "ctypes",
    "curses",
    "dataclasses",
    "datetime",
    "dbm",
    "decimal",
    "difflib",
    "dis",
    "doctest",
    "email",
    "encodings",
    "ensurepip",
    "enum",
    "errno",
    "faulthandler",
    "fcntl",
    "filecmp",
    "fileinput",
    "fnmatch",
    "fractions",
    "ftplib",
    "functools",
    "gc",
    "genericpath",
    "getopt",
    "getpass",
    "gettext",
    "glob",
    "graphlib",
    "grp",
    "gzip",
    "hashlib",
    "heapq",
    "hmac",
    "html",
    "http",
    "idlelib",
    "imaplib",
    "importlib",
    "inspect",
    "io",
    "ipaddress",
    "itertools",
    "json",
    "keyword",
    "linecache",
    "locale",
    "logging",
    "lzma",
    "mailbox",
    "marshal",
    "math",
    "mimetypes",
    "mmap",
    "modulefinder",
    "msvcrt",
    "multiprocessing",
    "netrc",
    "nt",
    "ntpath",
    "nturl2path",
    "numbers",
    "opcode",
    "operator",
    "optparse",
    "os",
    "pathlib",
    "pdb",
    "pickle",
    "pickletools",
    "pkgutil",
    "platform",
    "plistlib",
    "poplib",
    "posix",
    "posixpath",
    "pprint",
    "profile",
    "pstats",
    "pty",
    "pwd",
    "py_compile",
    "pyclbr",
    "pydoc",
    "pydoc_data",
    "pyexpat",
    "queue",
    "quopri",
    "random",
    "re",
    "readline",
    "reprlib",
    "resource",
    "rlcompleter",
    "runpy",
    "sched",
    "secrets",
    "select",
    "selectors",
    "shelve",
    "shlex",
    "shutil",
    "signal",
    "site",
    "smtplib",
    "socket",
    "socketserver",
    "sqlite3",
    "sre_compile",
    "sre_constants",
    "sre_parse",
    "ssl",
    "stat",
    "statistics",
    "string",
    "stringprep",
    "struct",
    "subprocess",
    "symtable",
    "sys",
    "sysconfig",
    "syslog",
    "tabnanny",
    "tarfile",
    "tempfile",
    "termios",
    "textwrap",
    "this",
    "threading",
    "time",
    "timeit",
    "tkinter",
    "token",
    "tokenize",
    "tomllib",
    "trace",
    "traceback",
    "tracemalloc",
    "tty",
    "turtle",
    "turtledemo",
    "types",
    "typing",
    "unicodedata",
    "unittest",
    "urllib",
    "uuid",
    "venv",
    "warnings",
    "wave",
    "weakref",
    "webbrowser",
    "winreg",
    "winsound",
    "wsgiref",
    "xml",
    "xmlrpc",
    "zipapp",
    "zipfile",
    "zipimport",
    "zlib",
    "zoneinfo",
  ].map((name) => name.toLowerCase())
);

const SET_LIBERRPA_THIRD_PARTY_MODULE_NAMES = new Set<string>(
  [
    "psutil",
    "PIL",
    "win32clipboard",
    "win32cred",
    "win32gui",
    "win32con",
    "win32com",
    "win32api",
    "pythoncom",
    "pyperclip",
    "pathvalidate",
    "sqlalchemy",
    "pandas",
    "xlwings",
    "pyzipper",
    "pypdf",
    "fitz",
    "ftputil",
    "uiautomation",
    "pynput",
    "pyautogui",
    "imapclient",
    "mailparser",
    "yagmail",
    "json5",
    "easyocr",
    "requests",
    "screeninfo",
    "socketio",
    "flask",
    "flask_socketio",
    "keyboard",
    "pyWinhook",
    "pystray",
    "mss",
    "PyQt5",
  ].map((name) => name.toLowerCase())
);

export function getRiskyPyModuleNameReason(pyFile: string): string | null {
  let strNormalizedPath = pyFile.trim();

  if (strNormalizedPath.startsWith("./")) {
    strNormalizedPath = strNormalizedPath.slice(2);
  }

  const arrPathParts = strNormalizedPath.split("/");

  if (arrPathParts.length === 0 || arrPathParts[0] === "") {
    return null;
  }

  const strTopLevelName = arrPathParts[0].replace(/\.py$/i, "").toLowerCase();
  const strFileName = arrPathParts[arrPathParts.length - 1]
    .replace(/\.py$/i, "")
    .toLowerCase();

  if (SET_RESERVED_PACKAGE_NAMES.has(strTopLevelName)) {
    return `Python file path uses reserved top-level package name "${strTopLevelName}".`;
  }

  if (SET_RESERVED_PACKAGE_NAMES.has(strFileName)) {
    return `Python file name uses reserved package name "${strFileName}".`;
  }

  if (SET_LIBERRPA_EXPORTED_NAMES.has(strTopLevelName)) {
    return `Python file path uses a top-level name that conflicts with a LiberRPA command/module name "${strTopLevelName}".`;
  }

  if (SET_LIBERRPA_EXPORTED_NAMES.has(strFileName)) {
    return `Python file name conflicts with a LiberRPA command/module name "${strFileName}".`;
  }

  if (SET_PYTHON_STDLIB_MODULE_NAMES.has(strTopLevelName)) {
    return `Python file path may shadow Python standard library module "${strTopLevelName}".`;
  }

  if (SET_PYTHON_STDLIB_MODULE_NAMES.has(strFileName)) {
    return `Python file name may shadow Python standard library module "${strFileName}".`;
  }

  if (SET_LIBERRPA_THIRD_PARTY_MODULE_NAMES.has(strTopLevelName)) {
    return `Python file path may shadow a third-party package used by LiberRPA "${strTopLevelName}".`;
  }

  if (SET_LIBERRPA_THIRD_PARTY_MODULE_NAMES.has(strFileName)) {
    return `Python file name may shadow a third-party package used by LiberRPA "${strFileName}".`;
  }

  return null;
}
