# FileName: GenerateApiMd.py
__author__ = "Jiyan Hu"
__email__ = "mailwork.hu@gmail.com"
__license__ = "GNU Affero General Public License v3.0 or later"
__copyright__ = f"Copyright (C) 2025 {__author__}"

"""Generate the LiberRPA Code Reference from the Snippets catalog and API manifest."""

import textwrap
from typing import cast

from ApiConfig import DictCatalogSnippet, DictSnippetsCatalog
from GenerateApiData import DictApiItem, DictOverloadInfo
from SnippetUtils import find_project_root, get_snippets_dir, read_json


REFERENCE_INTRO = """# LiberRPA Code Reference

<!-- Generated by condaLibrary/snippets/GenerateApiMd.py. Do not edit this file manually. -->

This reference follows the categories and entries available in **LiberRPA Snippets Tree**.

It includes:

- LiberRPA Python APIs;
- Project values;
- LiberRPA-specific code templates;
- general Python convenience snippets provided by LiberRPA Editor.

Entries backed by LiberRPA Python APIs are generated from the corresponding Python objects and docstrings. Other entries document convenience snippets that are available through LiberRPA Snippets Tree.

Use your browser or editor search when you already know the API or Snippet name.
"""


def _parse_docstring_sections(docstring: str) -> dict[str, str]:
    sections: dict[str, list[str]] = {"description": []}
    current = "description"

    sectionHeaders = {
        "Parameters:": "parameters",
        "Returns:": "returns",
        "Raises:": "raises",
        "Examples:": "examples",
        "Example:": "examples",
        "Usage Example:": "usageExample",
        "Usage Examples:": "usageExample",
        "Notes:": "notes",
    }

    for line in docstring.splitlines():
        stripped = line.strip()
        sectionKey = sectionHeaders.get(stripped)
        if sectionKey is not None:
            current = sectionKey
            sections.setdefault(current, [])
            continue

        sections.setdefault(current, []).append(line)

    return {
        key: textwrap.dedent("\n".join(lines)).strip() for key, lines in sections.items()
    }


def _render_code_section(title: str, content: str) -> str:
    return f"{title}:\n\n```text\n{content}\n```"


def _render_python_section(title: str, content: str) -> str:
    return f"{title}:\n\n```python\n{content}\n```"


def _render_markdown_section(title: str, content: str) -> str:
    return f"{title}:\n\n{content}"


def _render_overload_signatures(overloads: list[DictOverloadInfo]) -> str:
    if not overloads:
        return ""

    lines: list[str] = []
    for overload in overloads:
        lines.append("@overload")
        lines.append(f"def {overload['signature']}: ...")

    return _render_python_section(title="Overload signatures", content="\n".join(lines))


def _render_description(description: str, overloads: list[DictOverloadInfo]) -> str:
    if not description:
        return ""

    sections = _parse_docstring_sections(description)
    parts: list[str] = []

    descriptionText = sections.get("description", "")
    if descriptionText:
        parts.append(descriptionText)

    overloadsText = _render_overload_signatures(overloads=overloads)
    if overloadsText:
        parts.append(overloadsText)

    parametersText = sections.get("parameters", "")
    if parametersText:
        parts.append(_render_code_section(title="Parameters", content=parametersText))

    returnsText = sections.get("returns", "")
    if returnsText:
        parts.append(_render_code_section(title="Returns", content=returnsText))

    raisesText = sections.get("raises", "")
    if raisesText:
        parts.append(_render_code_section(title="Raises", content=raisesText))

    notesText = sections.get("notes", "")
    if notesText:
        parts.append(_render_markdown_section(title="Notes", content=notesText))

    examplesText = sections.get("examples", "")
    if examplesText:
        parts.append(_render_markdown_section(title="Examples", content=examplesText))

    usageExampleText = sections.get("usageExample", "")
    if usageExampleText:
        parts.append(
            _render_markdown_section(title="Usage Example", content=usageExampleText)
        )

    return "\n\n".join(parts)


def _load_api_manifest_by_title() -> dict[str, DictApiItem]:
    manifestPath = get_snippets_dir() / "api_manifest.json"

    apiManifest = cast(list[DictApiItem], read_json(manifestPath, list))
    return {item["title"]: item for item in apiManifest}


def _group_snippets_by_category(
    catalog: DictSnippetsCatalog,
) -> dict[str, list[tuple[str, DictCatalogSnippet]]]:
    snippetsByCategory: dict[str, list[tuple[str, DictCatalogSnippet]]] = {
        category: [] for category in catalog["categoryOrder"]
    }

    for title, snippet in catalog["snippets"].items():
        category = snippet["category"]
        if category not in snippetsByCategory:
            raise ValueError(
                f"Snippet {title!r} uses category {category!r}, but the category is missing from categoryOrder."
            )

        snippetsByCategory[category].append((title, snippet))

    return snippetsByCategory


def _get_category_anchor(category: str) -> str:
    """Return the GitHub Markdown anchor used by the current built-in category names."""
    return category.lower().replace(" ", "-")


def _render_contents(
    catalog: DictSnippetsCatalog,
    snippetsByCategory: dict[str, list[tuple[str, DictCatalogSnippet]]],
) -> str:
    lines = ["## Contents", ""]

    for category in catalog["categoryOrder"]:
        if not snippetsByCategory[category]:
            continue
        lines.append(f"- [{category}](#{_get_category_anchor(category)})")

    return "\n".join(lines)


def _generate_reference_markdown(catalog: DictSnippetsCatalog) -> str:
    markdownParts: list[str] = [REFERENCE_INTRO.strip()]
    apiManifestByTitle = _load_api_manifest_by_title()
    snippetsByCategory = _group_snippets_by_category(catalog=catalog)

    markdownParts.append(
        _render_contents(catalog=catalog, snippetsByCategory=snippetsByCategory)
    )

    for category in catalog["categoryOrder"]:
        categorySnippets = snippetsByCategory[category]
        if not categorySnippets:
            continue

        markdownParts.append(f"## {category}")

        for title, snippet in categorySnippets:
            markdownParts.append(f"### {snippet['label']}")

            apiItem = apiManifestByTitle.get(title)
            overloads = apiItem.get("overloads", []) if apiItem is not None else []

            description = snippet.get("description", "")
            renderedDescription = _render_description(
                description=description, overloads=overloads
            )
            if not renderedDescription:
                raise ValueError(f"Snippet {title!r} has no description.")

            markdownParts.append(renderedDescription)

    return "\n\n".join(markdownParts).strip() + "\n"


def main() -> None:
    projectRoot = find_project_root()
    snippetsDir = get_snippets_dir()

    catalogPath = snippetsDir / "snippets_catalog.json"
    catalog = cast(DictSnippetsCatalog, read_json(catalogPath, dict))
    referenceMarkdown = _generate_reference_markdown(catalog=catalog)
    outputPath = projectRoot.parent / "docs" / "Reference.md"
    outputPath.parent.mkdir(parents=True, exist_ok=True)
    outputPath.write_text(referenceMarkdown, encoding="utf-8")

    print(f"Generated LiberRPA Code Reference: {outputPath}")


if __name__ == "__main__":
    main()
