# FileName: UiInterface.py
__author__ = "Jiyan Hu"
__email__ = "mailwork.hu@gmail.com"
__license__ = "GNU Affero General Public License v3.0 or later"
__copyright__ = f"Copyright (C) 2025 {__author__}"


from liberrpa.Logging import Log
from liberrpa.UI._Overlay import create_overlay
from liberrpa.UI._Image import find_image
import liberrpa.UI._UiElement as _UiElement
from liberrpa.UI._UiAutomation import get_children_control_recursive
from liberrpa.UI._UiDict import (
    DictSpecHtml,
    DictUiaAttr,
    DictHtmlAttr,
    DictImageAttr,
    DictPositionAndSize,
    SelectorWindow,
    SelectorUia,
    SelectorHtml,
    SelectorImage,
)
from liberrpa.Common._TypedValue import StrPath
from liberrpa.UI._SelectorValidation import as_selector_uia, as_selector_html, validate_selector
from liberrpa.UI._TerminableThread import timeout_kill_thread
from liberrpa.UI._OperationLock import lock_ui_operation
from liberrpa.Common._Exception import (
    UiElementNotFoundError,
    UiTimeoutError,
    UiElementAppearTimeoutError,
    UiElementDisappearTimeoutError,
    UiOperationError,
    UiSelectorError,
    ChromeElementNotFoundError,
)
from liberrpa.Common._Chrome import (
    get_parent_element_attr,
    get_children_element_attr,
    set_element_text as Chrome_set_element_text,
    set_check_state as Chrome_set_check_state,
    get_selection as Chrome_get_selection,
    set_selection as Chrome_set_selection,
)
from liberrpa.Basic import delay

from time import monotonic
import uiautomation
import os
from PIL import Image
import mss
from pathlib import Path
from typing import Literal, cast, overload


_WAIT_RETRY_INTERVAL = 200


def _decrease_timeout_with_retry_delay(timeout: int, timeStart: float) -> int:
    timeUsed = int((monotonic() - timeStart) * 1000)
    timeout -= timeUsed

    if timeout <= 0:
        return timeout

    retryDelay = min(_WAIT_RETRY_INTERVAL, timeout)
    delay(retryDelay)
    timeout -= retryDelay

    return timeout


def _highlight(
    selector: SelectorWindow | SelectorUia | SelectorHtml | SelectorImage,
    color: str = "red",
    duration: int = 1000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> None:
    _, dictTarget = _UiElement.get_element_with_pre_delay(selector=selector, preDelay=preDelay)

    create_overlay(
        x=int(dictTarget["secondary-x"]),
        y=int(dictTarget["secondary-y"]),
        width=int(dictTarget["secondary-width"]),
        height=int(dictTarget["secondary-height"]),
        color=color,
        duration=duration,
    )

    delay(postDelay)


@Log.trace()
@lock_ui_operation
def highlight(
    selector: SelectorWindow | SelectorUia | SelectorHtml | SelectorImage,
    color: Literal["red", "green", "blue", "yellow", "purple", "pink", "black"] = "red",
    duration: int = 1000,
    timeout: int = 10000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> None:
    """
    Draw a rectangle around the element.

    Parameters:
        selector: A selector dictionary generated by UI Analyzer for locating an element. You can edit it to make it more concise or more robust in different situations.
        color: The color of the highlight border. Available options are "red", "green", "blue", "yellow", "purple", "pink", "black".
        duration: The time in milliseconds for which the highlight should remain visible on the screen.
        timeout: Maximum time allowed for normal completion, in milliseconds. Values below 3000 are treated as 3000. The actual elapsed time may be longer if LiberRPA enters its hard-timeout fallback before raising a timeout-related exception.
        preDelay: Time to wait before performing the action, in milliseconds.
        postDelay: Time to wait after performing the action, in milliseconds.
    """
    timeout = _UiElement.check_set_timeout(timeout=timeout)

    return timeout_kill_thread(timeout=timeout)(_highlight)(
        selector,
        color,
        duration,
        preDelay,
        postDelay,
    )


def _screenshot(
    selector: SelectorWindow | SelectorUia | SelectorHtml | SelectorImage,
    saveFilePath: StrPath,
    offsetX: int = 0,
    offsetY: int = 0,
    width: int | None = None,
    height: int | None = None,
    override: bool = False,
    preDelay: int = 300,
    postDelay: int = 200,
) -> str:

    if not override and Path(saveFilePath).exists():
        raise FileExistsError(
            f"The argument 'override' is False, and the file '{Path(saveFilePath).absolute()}' already exists."
        )

    _, dictTarget = _UiElement.get_element_with_pre_delay(selector=selector, preDelay=preDelay)

    # Define the bounding box of the area

    intXStart = int(dictTarget["secondary-x"]) + offsetX
    intYStart = int(dictTarget["secondary-y"]) + offsetY
    # If width or height is None, use the default size.
    if width == 0 or height == 0:
        raise ValueError("The arguments width or height cannot be 0.")

    if width is None:
        intXEnd = int(dictTarget["secondary-x"]) + int(dictTarget["secondary-width"]) + offsetX
    else:
        intXEnd = int(dictTarget["secondary-x"]) + width + offsetX

    if height is None:
        intYEnd = int(dictTarget["secondary-y"]) + int(dictTarget["secondary-height"]) + offsetY
    else:
        intYEnd = int(dictTarget["secondary-y"]) + height + offsetY

    # Capture the screen by mss due to the coordinates may be negative.
    with mss.mss() as sct:
        # Define the region for the screenshot
        monitor = {"top": intYStart, "left": intXStart, "width": intXEnd - intXStart, "height": intYEnd - intYStart}
        # Grab the data
        screenshotTemp = sct.grab(monitor)
        # Convert the raw pixel data to a PIL Image
        imgTemp = Image.frombytes("RGB", screenshotTemp.size, screenshotTemp.rgb)

    Path(saveFilePath).parent.mkdir(parents=True, exist_ok=True)
    imgTemp.save(os.fspath(saveFilePath))

    delay(postDelay)

    return str(Path(saveFilePath).absolute())


@Log.trace()
@lock_ui_operation
def screenshot(
    selector: SelectorWindow | SelectorUia | SelectorHtml | SelectorImage,
    saveFilePath: StrPath,
    offsetX: int = 0,
    offsetY: int = 0,
    width: int | None = None,
    height: int | None = None,
    override: bool = False,
    timeout: int = 10000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> str:
    """
    Capture a screenshot of the element's area and save it.

    Parameters:
        selector: A selector dictionary generated by UI Analyzer for locating an element. You can edit it to make it more concise or more robust in different situations.
        saveFilePath: The file path where the screenshot will be saved. Accepts str or PathLike[str].
        offsetX: The horizontal offset in pixels from the top-left corner of the element to start capturing the screenshot.
        offsetY: The vertical offset in pixels from the top-left corner of the element to start capturing the screenshot.
        width: The width of the screenshot in pixels. If None, the width of the element will be used.
        height: The height of the screenshot in pixels. If None, the height of the element will be used.
        override: If True, will overwrite an existing file at saveFilePath.
        timeout: Maximum time allowed for normal completion, in milliseconds. Values below 3000 are treated as 3000. The actual elapsed time may be longer if LiberRPA enters its hard-timeout fallback before raising a timeout-related exception.
        preDelay: Time to wait before performing the action, in milliseconds.
        postDelay: Time to wait after performing the action, in milliseconds.

    Returns:
        str: The absolute path of the saved screenshot.
    """

    timeout = _UiElement.check_set_timeout(timeout=timeout)
    return str(
        timeout_kill_thread(timeout=timeout)(_screenshot)(
            selector,
            saveFilePath,
            offsetX,
            offsetY,
            width,
            height,
            override,
            preDelay,
            postDelay,
        )
    )


@Log.trace()
@lock_ui_operation
def get_image_position(
    filePath: StrPath,
    region: tuple[int, int, int, int] | None = None,
    confidence: float = 0.95,
    grayscale: bool = True,
    limit: int = 1,
    highlight: bool = False,
) -> list[DictPositionAndSize]:
    """
    Searches for an image on the screen and returns the coordinates of matched regions.

    Parameters:
        filePath: The path of the image file to locate. Accepts str or PathLike[str].
        region: A tuple (x, y, width, height) defining the search area. If None, searches the entire screen.
        confidence: A float (0.0 to 1.0) indicating the required match accuracy.
        grayscale: If True, searches in grayscale mode for faster detection.
        limit: The maximum number of matches to return.
        highlight: Whether highlight the matched position.

    Returns:
        list[DictPositionAndSize]: A list of dictionaries containing the x, y, width, and height of the matched images: {'x': <class 'int'>, 'y': <class 'int'>, 'width': <class 'int'>, 'height': <class 'int'>}
    """

    if limit < 1:
        raise ValueError("The argument 'limit' should be greater than 0.")

    listTemp: list[DictImageAttr] = find_image(
        fileNameOrPath=filePath,
        region=region,
        confidence=confidence,
        grayscale=grayscale,
        limit=limit,
        moveFile=False,
        inScreenshotFolder=False,
    )

    listReturn: list[DictPositionAndSize] = []
    for item in listTemp:
        listReturn.append({
            "x": int(item["secondary-x"]),
            "y": int(item["secondary-y"]),
            "width": int(item["secondary-width"]),
            "height": int(item["secondary-height"]),
        })
        if highlight:
            create_overlay(
                x=int(item["secondary-x"]),
                y=int(item["secondary-y"]),
                width=int(item["secondary-width"]),
                height=int(item["secondary-height"]),
                color="red",
                duration=200,
                label="",
            )

    return listReturn


def _check_exists(
    selector: SelectorWindow | SelectorUia | SelectorHtml | SelectorImage,
) -> bool:

    try:
        _, _ = _UiElement.get_element(selector=selector)
    except (UiElementNotFoundError, ChromeElementNotFoundError):
        return False
    else:
        return True


@Log.trace()
@lock_ui_operation
def check_exists(
    selector: SelectorWindow | SelectorUia | SelectorHtml | SelectorImage,
    timeout: int = 10000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> bool:
    """
    Check if an element exists.

    Temporary UI/Chrome errors may be retried during the timeout period. If the element is still not found after timeout, returns False.
    If the selector is invalid or another non-not-found error still occurs at timeout, that exception is raised.

    Parameters:
        selector: The dictionary for locating an element.
        timeout: Maximum time to keep checking whether the element exists, in milliseconds. Values below 3000 are treated as 3000. The actual elapsed time may be longer if an individual UI check enters its hard-timeout fallback.
        preDelay: Time to wait before performing the action, in milliseconds.
        postDelay: Time to wait after performing the action, in milliseconds.

    Returns:
        bool: True if the element exists within the specified timeout, False if it is not found.
    """

    timeout = _UiElement.check_set_timeout(timeout=timeout)
    lastException: Exception | None = None

    delay(preDelay)

    try:
        while True:
            timeStart = monotonic()

            try:
                if bool(timeout_kill_thread(timeout=timeout)(_check_exists)(selector)):
                    return True

                lastException = None

            except UiSelectorError:
                raise

            except (UiElementNotFoundError, ChromeElementNotFoundError, UiTimeoutError) as e:
                # Not found or one check timed out. For check_exists(), this means "not confirmed existing yet".
                lastException = e

            except Exception as e:
                # Retry temporary errors during timeout, but do not hide them forever.
                lastException = e
                Log.verbose(f"check_exists retry after exception: {e}")

            timeout = _decrease_timeout_with_retry_delay(timeout=timeout, timeStart=timeStart)
            if timeout <= 0:
                if lastException is None:
                    return False

                if isinstance(lastException, (UiElementNotFoundError, ChromeElementNotFoundError, UiTimeoutError)):
                    return False

                raise lastException

    finally:
        delay(postDelay)


@Log.trace()
@lock_ui_operation
def wait_appear(
    selector: SelectorWindow | SelectorUia | SelectorHtml | SelectorImage,
    timeout: int = 10000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> None:
    """
    Wait for an element to appear.

    Parameters:
        selector: The dictionary for locating an element.
        timeout: Maximum time to wait for the element to appear, in milliseconds. Values below 3000 are treated as 3000. The actual elapsed time may be longer if an individual UI check enters its hard-timeout fallback.
        preDelay: Time to wait before performing the action, in milliseconds.
        postDelay: Time to wait after performing the action, in milliseconds.
    """

    timeout = _UiElement.check_set_timeout(timeout=timeout)
    timeoutOriginal = timeout
    lastException: Exception | None = None

    delay(preDelay)

    try:
        while True:
            timeStart = monotonic()

            try:
                if bool(timeout_kill_thread(timeout=timeout)(_check_exists)(selector)):
                    return None

                lastException = None

            except UiSelectorError:
                raise

            except (UiElementNotFoundError, ChromeElementNotFoundError, UiTimeoutError) as e:
                lastException = e

            except Exception as e:
                lastException = e
                Log.verbose(f"wait_appear retry after exception: {e}")

            timeout = _decrease_timeout_with_retry_delay(timeout=timeout, timeStart=timeStart)
            if timeout <= 0:
                if lastException is None:
                    raise UiElementAppearTimeoutError(
                        f"Timeout exceeded for UI element to appear. timeout={timeoutOriginal}, selector: {selector}"
                    )

                if isinstance(
                    lastException,
                    (UiElementNotFoundError, ChromeElementNotFoundError, UiTimeoutError),
                ):
                    raise UiElementAppearTimeoutError(
                        f"Timeout exceeded for UI element to appear. timeout={timeoutOriginal}, selector: {selector}"
                    ) from lastException

                raise lastException

    finally:
        delay(postDelay)


@Log.trace()
@lock_ui_operation
def wait_disappear(
    selector: SelectorWindow | SelectorUia | SelectorHtml | SelectorImage,
    timeout: int = 10000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> None:
    """
    Wait for an element to disappear.

    Parameters:
        selector: The dictionary for locating an element.
        timeout: Maximum time to wait for the element to disappear, in milliseconds. Values below 3000 are treated as 3000. The actual elapsed time may be longer if an individual UI check enters its hard-timeout fallback.
        preDelay: Time to wait before performing the action, in milliseconds.
        postDelay: Time to wait after performing the action, in milliseconds.
    """

    timeout = _UiElement.check_set_timeout(timeout=timeout)
    timeoutOriginal = timeout
    lastException: Exception | None = None
    lastCheckStatus: Literal["exists", "not_found", "error"] | None = None

    delay(preDelay)

    try:
        while True:
            timeStart = monotonic()

            try:
                boolExists = bool(timeout_kill_thread(timeout=timeout)(_check_exists)(selector))

                if boolExists:
                    lastCheckStatus = "exists"
                    lastException = None
                else:
                    lastCheckStatus = "not_found"
                    return None

            except UiSelectorError:
                raise

            except (UiElementNotFoundError, ChromeElementNotFoundError):
                lastCheckStatus = "not_found"
                return None

            except UiTimeoutError as e:
                # One check consumed the remaining timeout or was killed.
                # For wait_disappear(), this means disappearance was not confirmed.
                lastCheckStatus = "exists"
                lastException = e

            except Exception as e:
                # Temporary errors can be retried during timeout, but should not be hidden forever.
                lastCheckStatus = "error"
                lastException = e
                Log.verbose(f"wait_disappear retry after exception: {e}")

            timeout = _decrease_timeout_with_retry_delay(timeout=timeout, timeStart=timeStart)
            if timeout <= 0:
                if lastCheckStatus == "exists":
                    raise UiElementDisappearTimeoutError(
                        f"Timeout exceeded for UI element to disappear. timeout={timeoutOriginal}, selector: {selector}"
                    ) from lastException

                if lastCheckStatus == "error" and lastException is not None:
                    raise lastException

                raise UiElementDisappearTimeoutError(
                    f"Timeout exceeded for UI element to disappear. timeout={timeoutOriginal}, selector: {selector}"
                )

    finally:
        delay(postDelay)


def _get_parent(
    selector: SelectorUia | SelectorHtml,
    upwardLevel: int = 1,
    timeout: int = 10000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> SelectorWindow | SelectorUia | SelectorHtml:

    if selector.get("category") == "image":
        raise UiOperationError("Not support getting an image element's parent.")

    if selector.get("category") is None:
        raise UiOperationError("Not support getting an UIA window element's parent.")

    if not isinstance(upwardLevel, int) or upwardLevel < 1:
        raise ValueError("The argument 'upwardLevel' should be an integer equal to or greater than 1.")

    if selector.get("category") == "html":
        _UiElement.activate_element_window(selector=selector)
        selectorParentHtml: SelectorHtml = {
            "window": selector["window"],
            "category": "html",
            "specification": get_parent_element_attr(
                htmlSelector=as_selector_html(selector=selector)["specification"],
                upwardLevel=upwardLevel,
                preDelay=preDelay,
                timeout=timeout,
            ),
        }

        delay(postDelay)
        return selectorParentHtml

    # uia
    uiTarget, _ = _UiElement.get_element_with_pre_delay(selector=selector, preDelay=preDelay)
    for i in range(1, upwardLevel + 1, 1):
        if isinstance(uiTarget, uiautomation.Control):
            # Only choose non-Desktop controls that have 'Name'.
            while True:
                uiTarget = uiTarget.GetParentControl()
                if uiTarget is None or (uiTarget.ControlTypeName == "PaneControl" and uiTarget.ClassName == "#32769"):
                    # If have no parent control or its parent is Desktop
                    raise UiElementNotFoundError(f"Not found its parent element at upwardLevel {i}.")
                elif uiTarget.Name is None or uiTarget.Name == "":
                    # It has no 'Name'.
                    continue
                else:
                    selectorParentUia: SelectorWindow | SelectorUia = _UiElement.get_control_selector(control=uiTarget)
                    Log.debug(f"Found parent at upwardLevel {i}." + str(selectorParentUia))
                    break
    delay(postDelay)

    return selectorParentUia


@overload
def get_parent(
    selector: SelectorHtml,
    upwardLevel: int = 1,
    timeout: int = 10000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> SelectorHtml: ...


@overload
def get_parent(
    selector: SelectorUia,
    upwardLevel: int = 1,
    timeout: int = 10000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> SelectorWindow | SelectorUia: ...


@Log.trace()
@lock_ui_operation
def get_parent(
    selector: SelectorUia | SelectorHtml,
    upwardLevel: int = 1,
    timeout: int = 10000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> SelectorWindow | SelectorUia | SelectorHtml:
    """
    Get the selector of an element's parent. Only support SelectorUia and SelectorHtml.

    Parameters:
        selector: A selector dictionary generated by UI Analyzer for locating an element. You can edit it to make it more concise or more robust in different situations.
        upwardLevel: The upward layer to find its parent element.
        timeout: Maximum time allowed for normal completion, in milliseconds. Values below 3000 are treated as 3000. The actual elapsed time may be longer if LiberRPA enters its hard-timeout fallback before raising a timeout-related exception.
        preDelay: Time to wait before performing the action, in milliseconds.
        postDelay: Time to wait after performing the action, in milliseconds.

    Returns:
        SelectorWindow | SelectorUia | SelectorHtml: The parent element's selector.
    """

    timeout = _UiElement.check_set_timeout(timeout=timeout)
    return timeout_kill_thread(timeout=timeout)(_get_parent)(
        selector,
        upwardLevel,
        timeout,
        preDelay,
        postDelay,
    )


def _get_children(
    selector: SelectorWindow | SelectorUia | SelectorHtml,
    timeout: int = 30000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> list[SelectorUia] | list[SelectorHtml]:

    if selector.get("category") == "image":
        raise UiOperationError("Not support getting an image element's children.")

    if selector.get("category") == "html":
        _UiElement.activate_element_window(selector=selector)

        listSpecification: list[DictSpecHtml] = get_children_element_attr(
            htmlSelector=as_selector_html(selector=selector)["specification"],
            preDelay=preDelay,
            timeout=timeout,
        )

        controlTop = _UiElement.get_top_control(selectorWindowPart=selector["window"])
        selectorWindow: SelectorWindow = _UiElement.get_control_selector(control=controlTop)

        listSelectorsHtml: list[SelectorHtml] = []
        for item in listSpecification:
            listSelectorsHtml.append({"window": selectorWindow["window"], "category": "html", "specification": [item]})

        delay(postDelay)
        return listSelectorsHtml

    # uia
    uiTarget, _ = _UiElement.get_element_with_pre_delay(selector=selector, preDelay=preDelay)
    if isinstance(uiTarget, uiautomation.Control):
        # uia
        listControlChildren = get_children_control_recursive(control=uiTarget)
        listSelectorsUia: list[SelectorUia] = [
            as_selector_uia(selector=_UiElement.get_control_selector(control=childControl))
            for childControl in listControlChildren
        ]

    delay(postDelay)

    return listSelectorsUia


@overload
def get_children(
    selector: SelectorHtml,
    timeout: int = 30000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> list[SelectorHtml]: ...


@overload
def get_children(
    selector: SelectorWindow | SelectorUia,
    timeout: int = 30000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> list[SelectorUia]: ...


@Log.trace()
@lock_ui_operation
def get_children(
    selector: SelectorWindow | SelectorUia | SelectorHtml,
    timeout: int = 30000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> list[SelectorUia] | list[SelectorHtml]:
    """
    Get selectors of child elements. Only supports SelectorWindow, SelectorUia, and SelectorHtml.

    For HTML elements, this function returns selectors of direct child elements.
    For UIA elements, unnamed container controls may be skipped, so the returned selectors may point to named descendant controls instead of only direct children.

    Parameters:
        selector: A selector dictionary generated by UI Analyzer for locating an element. You can edit it to make it more concise or more robust in different situations.
        timeout: Maximum time allowed for normal completion, in milliseconds. Values below 3000 are treated as 3000. The actual elapsed time may be longer if LiberRPA enters its hard-timeout fallback before raising a timeout-related exception.
        preDelay: Time to wait before performing the action, in milliseconds.
        postDelay: Time to wait after performing the action, in milliseconds.

    Returns:
        list[SelectorUia] | list[SelectorHtml]: Selectors of child elements. For UIA, unnamed container controls may be skipped and named descendants may be returned.
    """

    timeout = _UiElement.check_set_timeout(timeout=timeout)
    return timeout_kill_thread(timeout=timeout)(_get_children)(
        selector,
        timeout,
        preDelay,
        postDelay,
    )


def _get_attr_dictionary(
    selector: SelectorWindow | SelectorUia | SelectorHtml | SelectorImage,
    preDelay: int = 300,
    postDelay: int = 200,
) -> DictUiaAttr | DictHtmlAttr | DictImageAttr:
    _, dictTarget = _UiElement.get_element_with_pre_delay(selector=selector, preDelay=preDelay)

    delay(postDelay)
    return dictTarget


@overload
def get_attr_dictionary(
    selector: SelectorWindow | SelectorUia,
    timeout: int = 10000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> DictUiaAttr: ...


@overload
def get_attr_dictionary(
    selector: SelectorHtml,
    timeout: int = 10000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> DictHtmlAttr: ...


@overload
def get_attr_dictionary(
    selector: SelectorImage,
    timeout: int = 10000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> DictImageAttr: ...


@Log.trace()
@lock_ui_operation
def get_attr_dictionary(
    selector: SelectorWindow | SelectorUia | SelectorHtml | SelectorImage,
    timeout: int = 10000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> DictUiaAttr | DictHtmlAttr | DictImageAttr:
    """
    Get a dictionary contains all attributes of the element.

    Parameters:
        selector: A selector dictionary generated by UI Analyzer for locating an element. You can edit it to make it more concise or more robust in different situations.
        timeout: Maximum time allowed for normal completion, in milliseconds. Values below 3000 are treated as 3000. The actual elapsed time may be longer if LiberRPA enters its hard-timeout fallback before raising a timeout-related exception.
        preDelay: Time to wait before performing the action, in milliseconds.
        postDelay: Time to wait after performing the action, in milliseconds.

    Returns:
        DictUiaAttr | DictHtmlAttr | DictImageAttr: The attributes dictionary of the element, note some attributes with the prefix of "secondary-".
    """

    timeout = _UiElement.check_set_timeout(timeout=timeout)

    return timeout_kill_thread(timeout=timeout)(_get_attr_dictionary)(
        selector,
        preDelay,
        postDelay,
    )


def _get_control_text_recursive(control: uiautomation.Control) -> list[str]:
    listText: list[str] = []

    # Get text from Name and HelpText which are common properties
    if control.Name:
        listText.append(control.Name)
    if control.HelpText:
        listText.append(control.HelpText)

    # Try to retrieve text using ValuePattern if available
    pattern = cast(
        uiautomation.ValuePattern | None,
        control.GetPattern(uiautomation.PatternId.ValuePattern),
    )
    if pattern is not None and pattern.Value:
        listText.append(pattern.Value)
    else:
        # If ValuePattern is not available or provides no text, check TextPattern
        pattern = cast(
            uiautomation.TextPattern | None,
            control.GetPattern(uiautomation.PatternId.TextPattern),
        )
        if pattern is not None:
            strText = pattern.DocumentRange.GetText(-1)
            if strText:
                listText.append(strText)

    # Recursively process child controls
    for child in control.GetChildren():
        listText.extend(_get_control_text_recursive(control=child))

    return listText


def _get_text(
    selector: SelectorWindow | SelectorUia | SelectorHtml,
    preDelay: int = 300,
    postDelay: int = 200,
) -> tuple[list[str], str]:

    if selector.get("category") == "image":
        raise UiOperationError("Not support getting text by the function, consider using OCR.")

    uiTarget, dictTarget = _UiElement.get_element_with_pre_delay(selector=selector, preDelay=preDelay)

    listText: list[str] = []

    if isinstance(uiTarget, uiautomation.Control):
        listText = _get_control_text_recursive(control=uiTarget)
        delay(postDelay)
        return (listText, "\n".join(listText))
    else:
        # html
        delay(postDelay)
        innerText = dictTarget.get("innerText")
        value = dictTarget.get("value")

        if isinstance(innerText, str) and innerText:
            strTemp = innerText
        elif isinstance(value, str) and value:
            strTemp = value
        else:
            strTemp = ""
        return ([strTemp], strTemp)


@Log.trace()
@lock_ui_operation
def get_text(
    selector: SelectorWindow | SelectorUia | SelectorHtml,
    timeout: int = 10000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> tuple[list[str], str]:
    """
    Get all text of the element. Only support SelectorWindow, SelectorUia and SelectorHtml.

    Parameters:
        selector: A selector dictionary generated by UI Analyzer for locating an element. You can edit it to make it more concise or more robust in different situations.
        timeout: Maximum time allowed for normal completion, in milliseconds. Values below 3000 are treated as 3000. The actual elapsed time may be longer if LiberRPA enters its hard-timeout fallback before raising a timeout-related exception.
        preDelay: Time to wait before performing the action, in milliseconds.
        postDelay: Time to wait after performing the action, in milliseconds.

    Returns:
        tuple[list[str], str]: A tuple contains the all children element's text(if it's an uia element) and all text.
    """

    timeout = _UiElement.check_set_timeout(timeout=timeout)

    return timeout_kill_thread(timeout=timeout)(_get_text)(
        selector,
        preDelay,
        postDelay,
    )


def _set_text(
    selector: SelectorUia | SelectorHtml,
    text: str,
    timeout: int = 10000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> None:

    if selector.get("category") == "image":
        raise UiOperationError("Not support setting text in an image element.")

    if selector.get("category") is None:
        raise UiOperationError("Not support setting text in an UIA window element.")

    if selector.get("category") == "html":
        _UiElement.activate_element_window(selector=selector)

        Chrome_set_element_text(
            htmlSelector=as_selector_html(selector=selector)["specification"],
            text=text,
            clearBeforeWrite=True,
            validateText=False,
            preDelay=preDelay,
            timeout=timeout,
        )

        delay(postDelay)
        return None

    # uia
    uiTarget, _ = _UiElement.get_element_with_pre_delay(selector=selector, preDelay=preDelay)

    if isinstance(uiTarget, uiautomation.Control):
        pattern = cast(
            uiautomation.ValuePattern | None,
            uiTarget.GetPattern(uiautomation.PatternId.ValuePattern),
        )
        if pattern is not None and uiTarget.IsEnabled:
            pattern.SetValue(text)
            delay(postDelay)
            return None

    # Other elements don't support setting text and not be checked before.

    raise UiOperationError(
        f"The element does not support setting text or LiberRPA does not have permission. selector: {selector}"
    )


@Log.trace()
@lock_ui_operation
def set_text(
    selector: SelectorUia | SelectorHtml,
    text: str,
    timeout: int = 10000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> None:
    """
    Set an element's text by its API instead of inputting by keyboard. Only support SelectorUia and SelectorHtml.

    Parameters:
        selector: A selector dictionary generated by UI Analyzer for locating an element. You can edit it to make it more concise or more robust in different situations.
        text: The text to be set.
        timeout: Maximum time allowed for normal completion, in milliseconds. Values below 3000 are treated as 3000. The actual elapsed time may be longer if LiberRPA enters its hard-timeout fallback before raising a timeout-related exception.
        preDelay: Time to wait before performing the action, in milliseconds.
        postDelay: Time to wait after performing the action, in milliseconds.
    """

    timeout = _UiElement.check_set_timeout(timeout=timeout)

    return timeout_kill_thread(timeout=timeout)(_set_text)(
        selector,
        text,
        timeout,
        preDelay,
        postDelay,
    )


def _get_check_state(
    selector: SelectorUia | SelectorHtml,
    preDelay: int = 300,
    postDelay: int = 200,
) -> Literal["checked", "unchecked", "indeterminate"]:

    if selector.get("category") != "html" and selector.get("category") != "uia":
        raise UiOperationError("Can only get check state for html and uia non window elements which support check.")

    uiTarget, dictTarget = _UiElement.get_element_with_pre_delay(selector=selector, preDelay=preDelay)

    strReturn: str = ""

    if isinstance(uiTarget, uiautomation.Control):
        pattern = cast(
            uiautomation.TogglePattern | None,
            uiTarget.GetPattern(uiautomation.PatternId.TogglePattern),
        )

        if pattern is not None:
            intState: int = pattern.ToggleState
            if intState == 0:
                strReturn = "unchecked"
            elif intState == 1:
                strReturn = "checked"
            else:
                # intState == 2
                strReturn = "indeterminate"

            delay(postDelay)
            return strReturn

        raise UiOperationError(
            f"The element does not support getting check state or LiberRPA does not have permission. selector: {selector}"
        )
    else:
        # html
        if dictTarget.get("checked") == "false":
            strReturn = "unchecked"
        elif dictTarget.get("checked") == "true":
            strReturn = "checked"
        elif dictTarget.get("checked") == "indeterminate":
            strReturn = "indeterminate"
        else:
            raise UiOperationError(f"The element does not have the 'checked' attribute. selector: {selector}")

        delay(postDelay)
        return strReturn


@Log.trace()
@lock_ui_operation
def get_check_state(
    selector: SelectorUia | SelectorHtml,
    timeout: int = 10000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> Literal["checked", "unchecked", "indeterminate"]:
    """
    Get the check state of a checkbox or radio element. Only supports SelectorUia and SelectorHtml.

    Parameters:
        selector: A selector dictionary generated by UI Analyzer for locating an element. You can edit it to make it more concise or more robust in different situations.
        timeout: Maximum time allowed for normal completion, in milliseconds. Values below 3000 are treated as 3000. The actual elapsed time may be longer if LiberRPA enters its hard-timeout fallback before raising a timeout-related exception.
        preDelay: Time to wait before performing the action, in milliseconds.
        postDelay: Time to wait after performing the action, in milliseconds.

    Returns:
        str: one of "checked", "unchecked", "indeterminate"
    """

    timeout = _UiElement.check_set_timeout(timeout=timeout)

    return timeout_kill_thread(timeout=timeout)(_get_check_state)(
        selector,
        preDelay,
        postDelay,
    )


def _set_check_state(
    selector: SelectorUia | SelectorHtml,
    checkAction: Literal["checked", "unchecked", "toggle"] = "checked",
    timeout: int = 10000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> None:

    if selector.get("category") == "html":
        _UiElement.activate_element_window(selector=selector)

        # NOTE: Project highlightUI setting will not work for it. (Because the part not only get attributes.)

        Chrome_set_check_state(
            htmlSelector=as_selector_html(selector=selector)["specification"],
            checkAction=checkAction,
            preDelay=preDelay,
            timeout=timeout,
        )
        delay(postDelay)
        return None

    # uia
    uiTarget, _ = _UiElement.get_element_with_pre_delay(selector=selector, preDelay=preDelay)

    if isinstance(uiTarget, uiautomation.Control):
        pattern = cast(
            uiautomation.TogglePattern | None,
            uiTarget.GetPattern(uiautomation.PatternId.TogglePattern),
        )

        if pattern is not None:
            intState: int = pattern.ToggleState
            match checkAction:
                case "checked":
                    if intState == 1:
                        pass
                    elif intState == 0:
                        pattern.Toggle()
                    else:
                        # intState == 2
                        raise ValueError("The element's check state is 'indeterminate', can't be set.")
                case "unchecked":
                    if intState == 0:
                        pass
                    elif intState == 1:
                        pattern.Toggle()
                    else:
                        # intState == 2
                        raise ValueError("The element's check state is 'indeterminate', can't be set.")
                case "toggle":
                    pattern.Toggle()
                case _:
                    raise ValueError(
                        f"The argument checkAction({checkAction}) should be one of {['checked', 'unchecked', 'toggle']}"
                    )

            delay(postDelay)
            return None

    # image or uia element does't support setting check.
    raise UiOperationError(
        f"The element does not support setting check state or LiberRPA does not have permission. selector: {selector}"
    )


@Log.trace()
@lock_ui_operation
def set_check_state(
    selector: SelectorUia | SelectorHtml,
    checkAction: Literal["checked", "unchecked", "toggle"] = "checked",
    timeout: int = 10000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> None:
    """
    Set the check state of a checkbox or radio element. Only support SelectorUia and SelectorHtml.

    Parameters:
        selector: A selector dictionary generated by UI Analyzer for locating an element. You can edit it to make it more concise or more robust in different situations.
        checkAction: Options are "checked", "unchecked", or "toggle". Note that if an HTML element's checked state is "indeterminate", action "toggle" will modity it to "checked" or "unchecked", depend on its previous check state, same like the mouse single click.
        timeout: Maximum time allowed for normal completion, in milliseconds. Values below 3000 are treated as 3000. The actual elapsed time may be longer if LiberRPA enters its hard-timeout fallback before raising a timeout-related exception.
        preDelay: Time to wait before performing the action, in milliseconds.
        postDelay: Time to wait after performing the action, in milliseconds.
    """

    timeout = _UiElement.check_set_timeout(timeout=timeout)

    return timeout_kill_thread(timeout=timeout)(_set_check_state)(
        selector,
        checkAction,
        timeout,
        preDelay,
        postDelay,
    )


def _get_selection(
    selector: SelectorHtml,
    selectionType: Literal["text", "value", "index"] = "text",
    timeout: int = 10000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> str | int:

    validate_selector(selector=selector)

    if selectionType not in ["text", "value", "index"]:
        raise ValueError("The argument selectionType should be 'text', 'value' or 'index'.")

    if selector.get("category") != "html":
        raise UiOperationError("Can only get selected value for html <select> element.")

    # NOTE: Project highlightUI setting will not work for it. (Because the part not only get attributes.)

    selectorHtml = as_selector_html(selector)
    selectionTemp = Chrome_get_selection(
        htmlSelector=selectorHtml["specification"],
        selectionType=selectionType,
        preDelay=preDelay,
        timeout=timeout,
    )

    delay(postDelay)
    return selectionTemp


@overload
def get_selection(
    selector: SelectorHtml,
    selectionType: Literal["text"] = "text",
    timeout: int = 10000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> str: ...


@overload
def get_selection(
    selector: SelectorHtml,
    selectionType: Literal["value"],
    timeout: int = 10000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> str: ...


@overload
def get_selection(
    selector: SelectorHtml,
    selectionType: Literal["index"],
    timeout: int = 10000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> int: ...


@Log.trace()
@lock_ui_operation
def get_selection(
    selector: SelectorHtml,
    selectionType: Literal["text", "value", "index"] = "text",
    timeout: int = 10000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> str | int:
    """
    Get the selected option from an HTML <select> element.

    Only supports SelectorHtml and is intended for HTML <select> elements.

    Parameters:
        selector: The dictionary for locating an element. It is generated by UI Analyzer, and you can modify it to make it more concise or more suitable for different situations.
        selectionType: The type of selected option data to return. Options are "text", "value", and "index".
        timeout: Maximum time allowed for normal completion, in milliseconds. Values below 3000 are treated as 3000. The actual elapsed time may be longer if LiberRPA enters its hard-timeout fallback before raising a timeout-related exception.
        preDelay: Time to wait before performing the action, in milliseconds.
        postDelay: Time to wait after performing the action, in milliseconds.

    Returns:
        str | int: The selected option's text if selectionType is "text", its value if selectionType is "value", or its index if selectionType is "index".
    """

    timeout = _UiElement.check_set_timeout(timeout=timeout)

    return timeout_kill_thread(timeout=timeout)(_get_selection)(
        selector,
        selectionType,
        timeout,
        preDelay,
        postDelay,
    )


def _set_selection(
    selector: SelectorHtml,
    text: str | None = None,
    value: str | None = None,
    index: int | None = None,
    timeout: int = 10000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> None:

    validate_selector(selector=selector)

    provided = [text is not None, value is not None, index is not None]
    if sum(provided) != 1:
        raise ValueError("Exactly one of 'text', 'value', or 'index' must be non-null.")

    if selector.get("category") != "html":
        raise UiOperationError("Can only set selected value for html <select> element.")

    # NOTE: Project highlightUI setting will not work for it. (Because the part not only get attributes.)
    selectorHtml = as_selector_html(selector)
    Chrome_set_selection(
        htmlSelector=selectorHtml["specification"],
        text=text,
        value=value,
        index=index,
        preDelay=preDelay,
        timeout=timeout,
    )

    delay(postDelay)


@Log.trace()
@lock_ui_operation
def set_selection(
    selector: SelectorHtml,
    text: str | None = None,
    value: str | None = None,
    index: int | None = None,
    timeout: int = 10000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> None:
    """
    Set the selected option of an HTML <select> element.

    Only supports SelectorHtml and is intended for HTML <select> elements. Exactly one of
    text, value, or index must be provided.

    Parameters:
        selector: The dictionary for locating an element. It is generated by UI Analyzer, and you can modify it to make it more concise or more suitable for different situations.
        text: Select an option by its visible text. It is mutually exclusive with value and index.
        value: Select an option by its value attribute. It is mutually exclusive with text and index.
        index: Select an option by its index, starting from 0. It is mutually exclusive with text and value.
        timeout: Maximum time allowed for normal completion, in milliseconds. Values below 3000 are treated as 3000. The actual elapsed time may be longer if LiberRPA enters its hard-timeout fallback before raising a timeout-related exception.
        preDelay: Time to wait before performing the action, in milliseconds.
        postDelay: Time to wait after performing the action, in milliseconds.
    """

    timeout = _UiElement.check_set_timeout(timeout=timeout)

    return timeout_kill_thread(timeout=timeout)(_set_selection)(
        selector,
        text,
        value,
        index,
        timeout,
        preDelay,
        postDelay,
    )


if __name__ == "__main__":
    # from liberrpa._Selector import *
    from time import monotonic

    timeStart = monotonic()

    # print(
    #     get_image_position(
    #         filePath=R".\Screenshots\_20250129_185915.png",
    #         region=None,
    #         confidence=0.97,
    #         grayscale=True,
    #         limit=1,
    #         highlight=True,
    #     )
    # )

    # print(
    #     check_exists(
    #         selector={
    #             "window": {
    #                 "ProcessName": "chrome.exe",
    #                 "FrameworkId": "Win32",
    #                 "ControlTypeName": "PaneControl",
    #                 "Name": "处理报销单 - Google Chrome",
    #                 "ClassName": "Chrome_WidgetWin_1",
    #             },
    #             "category": "image",
    #             "specification": [{"FileName": "_20250129_185915.png", "Grayscale": "true", "Confidence": "0.97"}],
    #         },
    #         timeout=3000,
    #         preDelay=0,
    #         postDelay=0,
    #     )
    # )

    highlight(
        selector={
            "window": {
                "ProcessName": "notepad.exe",
                "FrameworkId": "Win32",
                "ControlTypeName": "WindowControl",
                "Name-regex": ".* - Notepad",
                "ClassName": "Notepad",
            },
            "category": "uia",
            "specification": [{"ControlTypeName": "EditControl", "Name": "Text Editor", "ClassName": "Edit"}],
        }
    )

    # print(get_selection(selector=selector,selectionType="text"))
    # set_selection(selector=selector, index=3)

    # print(get_check_state(selector=uiaGoogleBookmark1))

    # set_check_state(selector=uiaGoogleBookmark1, checkAction="toggle")

    # print(get_element_check_state(selector=selector))
    """ try:
        highlight(
            selector=uiaGoogleBookmark1,
            # selector=uiaWin2,
            # selector=htmlRpaChallenge2,
            # selector=image2,
            timeout=10000,
            preDelay=3000,
            postDelay=200,
            color="yellow",
            duration=1000,
        )
    except Exception as e:
        Log.error(e) """

    """ print(
        screenshot(
            selector=uiaGoogleBookmark1, saveFilePath="./temp.png", offsetX=0, offsetY=0, width=None, height=None, override=True
        )
    ) """
    # print(check_exists(selector=image1, timeout=5000))
    # wait_appear(selector=uiaGoogleBookmark2, timeout=3000)
    # wait_disappear(selector=image1, timeout=3000)
    # wait_disappear(selector=uiaGoogleBookmark2, timeout=3200)

    """ temp = get_parent(selector=image1, timeout=10000, preDelay=300, postDelay=200)
    print(temp) """

    # print(get_attr_dictionary(selector=image1))

    """ listText, strText = get_text(selector=image1)
    print(listText)
    print(strText) """
    # print(get_children(selector=image1))

    # set_text(selector=uiaWin1, text="123")
    # print(get_check_state(selector=uiaWin1))
    # set_check_state(selector=image1)
    # print(get_selection(selector=uiaGoogleBookmark1))
    # set_selection(selector=uiaGoogleBookmark1,text="1")

    """
    temp = get_parent(
        selector=image1, upwardLevel=2, timeout=10000, preDelay=300, postDelay=200
    )
    print(temp)
    highlight(selector=temp)
    # highlight(selector=selector)
    # print(get_parent(selector=selector, upwardLevel=1, timeout=10000, preDelay=300, postDelay=200))

    listTemp = get_children(selector=temp, timeout=30000, preDelay=300, postDelay=200)
    import json

    print(json.dumps(listTemp, ensure_ascii=False)) """

    """ uiTarget, dictTarget = _UiElement.get_element(selector=selector)
    listTemp = _get_children_control_recursive(control=uiTarget)
    for element in listTemp:
        print(element)
        create_overlay(element.BoundingRectangle.left, element.BoundingRectangle.top, element.BoundingRectangle.width(), element.BoundingRectangle.height(), color="red", duration=300) """
    # set_element_text(selector=selector, text="ssss测试")

    # print(get_element_text(selector=selector))
    # print(get_element_attributes_dictionary(selector=selector))
    #

    print("time used:", monotonic() - timeStart)
