# FileName: Window.py
__author__ = "Jiyan Hu"
__email__ = "mailwork.hu@gmail.com"
__license__ = "GNU Affero General Public License v3.0 or later"
__copyright__ = f"Copyright (C) 2025 {__author__}"


from liberrpa.Logging import Log
import liberrpa.UI._UiElement as _UiElement
from liberrpa.UI._UiDict import (
    DictPositionAndSize,
    DictUiaSecondaryAttr,
    SelectorWindow,
    SelectorUia,
    SelectorHtml,
    SelectorImage,
)
from liberrpa.UI._SelectorValidation import validate_selector
from liberrpa.UI._TerminableThread import timeout_kill_thread
from liberrpa.UI._OperationLock import lock_ui_operation
from liberrpa.Common._Exception import UiElementNotFoundError, UiOperationError
from liberrpa.UiInterface import check_exists
from liberrpa.Basic import delay

import uiautomation
import win32gui
import psutil
from typing import Literal, cast


def _extract_window_element(
    selector: SelectorWindow | SelectorUia | SelectorHtml | SelectorImage,
) -> SelectorWindow:
    validate_selector(selector=selector)
    selectorWindow: SelectorWindow = {"window": selector["window"]}
    return selectorWindow


def _close_window(
    selector: SelectorWindow | SelectorUia | SelectorHtml | SelectorImage,
    preDelay: int = 300,
    postDelay: int = 200,
) -> None:
    selectorWindow = _extract_window_element(selector=selector)
    uiTarget, _ = _UiElement.get_element_with_pre_delay(selector=selectorWindow, preDelay=preDelay)

    if isinstance(uiTarget, uiautomation.WindowControl) or isinstance(uiTarget, uiautomation.PaneControl):
        pattern = cast(
            uiautomation.WindowPattern | None,
            uiTarget.GetPattern(uiautomation.PatternId.WindowPattern),
        )
        if pattern is not None:
            pattern.Close()

            delay(postDelay)
            return None

    raise UiOperationError(
        f"The element does not support closing or LiberRPA does not have permission. selector: {selector}"
    )


@Log.trace()
@lock_ui_operation
def close_window(
    selector: SelectorWindow | SelectorUia | SelectorHtml | SelectorImage,
    timeout: int = 10000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> None:
    """
    Close the element's window.

    Parameters:
        selector: A selector dictionary generated by UI Analyzer for locating an element. You can edit it to make it more concise or more robust in different situations.
        timeout: Maximum time allowed for normal completion, in milliseconds. Values below 3000 are treated as 3000. The actual elapsed time may be longer if LiberRPA enters its hard-timeout fallback before raising a timeout-related exception.
        preDelay: Time to wait before performing the action, in milliseconds.
        postDelay: Time to wait after performing the action, in milliseconds.
    """
    timeout = _UiElement.check_set_timeout(timeout=timeout)

    return timeout_kill_thread(timeout=timeout)(_close_window)(
        selector,
        preDelay,
        postDelay,
    )


@Log.trace()
@lock_ui_operation
def check_window_exists(
    selector: SelectorWindow | SelectorUia | SelectorHtml | SelectorImage,
    timeout: int = 10000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> bool:
    """
    Check whether the element's window is existing.

    Parameters:
        selector: A selector dictionary generated by UI Analyzer for locating an element. You can edit it to make it more concise or more robust in different situations.
        timeout: Maximum time allowed for normal completion, in milliseconds. Values below 3000 are treated as 3000. The actual elapsed time may be longer if LiberRPA enters its hard-timeout fallback before raising a timeout-related exception.
        preDelay: Time to wait before performing the action, in milliseconds.
        postDelay: Time to wait after performing the action, in milliseconds.

    Returns:
        True if the element's window exists within the specified timeout, False otherwise.
    """

    selectorWindow = _extract_window_element(selector=selector)

    return check_exists(
        selector=selectorWindow,
        timeout=timeout,
        preDelay=preDelay,
        postDelay=postDelay,
    )


@Log.trace()
@lock_ui_operation
def get_active_window() -> SelectorWindow:
    """
    Get the selector of the currently active window.

    Returns:
        SelectorWindow: The selector of the currently active window.
    """
    hwnd = win32gui.GetForegroundWindow()
    if hwnd:
        control = uiautomation.ControlFromHandle(hwnd)
        if control is None:
            raise UiElementNotFoundError(f"Failed to get control from window handle: {hwnd}")

        return _UiElement.get_control_selector(control=control)
    else:
        raise UiElementNotFoundError("Not found a currently active window.")


@Log.trace()
@lock_ui_operation
def activate_element_window(selector: SelectorWindow | SelectorUia | SelectorHtml | SelectorImage) -> None:
    """
    Activate the element's window.

    Parameters:
        selector: A selector dictionary generated by UI Analyzer for locating an element. You can edit it to make it more concise or more robust in different situations.
    """
    _UiElement.activate_element_window(selector=selector)


def _set_window_state(
    selector: SelectorWindow | SelectorUia | SelectorHtml | SelectorImage,
    state: Literal["normal", "maximize", "minimize"] = "maximize",
    preDelay: int = 300,
    postDelay: int = 200,
) -> None:
    selectorWindow = _extract_window_element(selector=selector)
    uiTarget, _ = _UiElement.get_element_with_pre_delay(selector=selectorWindow, preDelay=preDelay)

    if isinstance(uiTarget, uiautomation.WindowControl) or isinstance(uiTarget, uiautomation.PaneControl):
        pattern = cast(
            uiautomation.WindowPattern | None,
            uiTarget.GetPattern(uiautomation.PatternId.WindowPattern),
        )
        if pattern is not None:
            match state:
                case "normal":
                    pattern.SetWindowVisualState(state=0)
                case "maximize":
                    pattern.SetWindowVisualState(state=1)
                case "minimize":
                    pattern.SetWindowVisualState(state=2)
                case _:
                    raise ValueError(
                        f"The argument state({state}) should be one of {['normal', 'maximize', 'minimize']}"
                    )

            delay(postDelay)
            return None

    raise UiOperationError(
        f"The element does not support setting window state or LiberRPA does not have permission. selector: {selector}"
    )


@Log.trace()
@lock_ui_operation
def set_window_state(
    selector: SelectorWindow | SelectorUia | SelectorHtml | SelectorImage,
    state: Literal["normal", "maximize", "minimize"] = "maximize",
    timeout: int = 10000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> None:
    """
    Set the element's window to normal, maximize or minimize.

    Parameters:
        selector: A selector dictionary generated by UI Analyzer for locating an element. You can edit it to make it more concise or more robust in different situations.
        state: Desired window state, can be 'normal', 'maximize', or 'minimize'.
        timeout: Maximum time allowed for normal completion, in milliseconds. Values below 3000 are treated as 3000. The actual elapsed time may be longer if LiberRPA enters its hard-timeout fallback before raising a timeout-related exception.
        preDelay: Time to wait before performing the action, in milliseconds.
        postDelay: Time to wait after performing the action, in milliseconds.
    """
    timeout = _UiElement.check_set_timeout(timeout=timeout)

    return timeout_kill_thread(timeout=timeout)(_set_window_state)(
        selector,
        state,
        preDelay,
        postDelay,
    )


def _get_window_position_and_size(
    selector: SelectorWindow | SelectorUia | SelectorHtml | SelectorImage,
    preDelay: int = 300,
    postDelay: int = 200,
) -> DictPositionAndSize:

    selectorWindow = _extract_window_element(selector=selector)
    _, dictTarget = _UiElement.get_element_with_pre_delay(selector=selectorWindow, preDelay=preDelay)

    dictReturn: DictPositionAndSize = {
        "x": int(dictTarget["secondary-x"]),
        "y": int(dictTarget["secondary-y"]),
        "width": int(dictTarget["secondary-width"]),
        "height": int(dictTarget["secondary-height"]),
    }

    delay(postDelay)
    return dictReturn


@Log.trace()
@lock_ui_operation
def get_window_position_and_size(
    selector: SelectorWindow | SelectorUia | SelectorHtml | SelectorImage,
    timeout: int = 10000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> DictPositionAndSize:
    """
    Get the position and size of the element's window.

    Parameters:
        selector: A selector dictionary generated by UI Analyzer for locating an element. You can edit it to make it more concise or more robust in different situations.
        timeout: Maximum time allowed for normal completion, in milliseconds. Values below 3000 are treated as 3000. The actual elapsed time may be longer if LiberRPA enters its hard-timeout fallback before raising a timeout-related exception.
        preDelay: Time to wait before performing the action, in milliseconds.
        postDelay: Time to wait after performing the action, in milliseconds.

    Returns:
        DictPositionAndSize: {'x': <class 'int'>, 'y': <class 'int'>, 'width': <class 'int'>, 'height': <class 'int'>}
    """
    timeout = _UiElement.check_set_timeout(timeout=timeout)

    return timeout_kill_thread(timeout=timeout)(_get_window_position_and_size)(
        selector,
        preDelay,
        postDelay,
    )


def _set_window_position(
    selector: SelectorWindow | SelectorUia | SelectorHtml | SelectorImage,
    x: int,
    y: int,
    preDelay: int = 300,
    postDelay: int = 200,
) -> None:

    selectorWindow = _extract_window_element(selector=selector)
    _, dictTarget = _UiElement.get_element_with_pre_delay(selector=selectorWindow, preDelay=preDelay)

    dictWindowAttr = cast(DictUiaSecondaryAttr, dictTarget)

    uiautomation.MoveWindow(
        handle=int(dictWindowAttr["secondary-NativeWindowHandle"]),
        x=x,
        y=y,
        width=int(dictTarget["secondary-width"]),
        height=int(dictTarget["secondary-height"]),
    )

    delay(postDelay)
    return None


@Log.trace()
@lock_ui_operation
def set_window_position(
    selector: SelectorWindow | SelectorUia | SelectorHtml | SelectorImage,
    x: int,
    y: int,
    timeout: int = 10000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> None:
    """
    Set the position of the element's window.

    Parameters:
        selector: A selector dictionary generated by UI Analyzer for locating an element. You can edit it to make it more concise or more robust in different situations.
        x: The horizontal position (in pixels) where the window's upper left corner should be moved to.
        y: The vertical position (in pixels) where the window's upper left corner should be moved to.
        timeout: Maximum time allowed for normal completion, in milliseconds. Values below 3000 are treated as 3000. The actual elapsed time may be longer if LiberRPA enters its hard-timeout fallback before raising a timeout-related exception.
        preDelay: Time to wait before performing the action, in milliseconds.
        postDelay: Time to wait after performing the action, in milliseconds.
    """
    timeout = _UiElement.check_set_timeout(timeout=timeout)

    return timeout_kill_thread(timeout=timeout)(_set_window_position)(
        selector,
        x,
        y,
        preDelay,
        postDelay,
    )


def _set_window_size(
    selector: SelectorWindow | SelectorUia | SelectorHtml | SelectorImage,
    width: int,
    height: int,
    preDelay: int = 300,
    postDelay: int = 200,
) -> None:

    selectorWindow = _extract_window_element(selector=selector)
    _, dictTarget = _UiElement.get_element_with_pre_delay(selector=selectorWindow, preDelay=preDelay)

    dictWindowAttr = cast(DictUiaSecondaryAttr, dictTarget)

    uiautomation.MoveWindow(
        handle=int(dictWindowAttr["secondary-NativeWindowHandle"]),
        x=int(dictTarget["secondary-x"]),
        y=int(dictTarget["secondary-y"]),
        width=width,
        height=height,
    )

    delay(postDelay)
    return None


@Log.trace()
@lock_ui_operation
def set_window_size(
    selector: SelectorWindow | SelectorUia | SelectorHtml | SelectorImage,
    width: int,
    height: int,
    timeout: int = 10000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> None:
    """
    Set the size of the element's window.

    Parameters:
        selector: A selector dictionary generated by UI Analyzer for locating an element. You can edit it to make it more concise or more robust in different situations.
        width: The new width of the window in pixels.
        height: The new height of the window in pixels.
        timeout: Maximum time allowed for normal completion, in milliseconds. Values below 3000 are treated as 3000. The actual elapsed time may be longer if LiberRPA enters its hard-timeout fallback before raising a timeout-related exception.
        preDelay: Time to wait before performing the action, in milliseconds.
        postDelay: Time to wait after performing the action, in milliseconds.
    """

    timeout = _UiElement.check_set_timeout(timeout=timeout)

    return timeout_kill_thread(timeout=timeout)(_set_window_size)(
        selector,
        width,
        height,
        preDelay,
        postDelay,
    )


def _get_window_pid(
    selector: SelectorWindow | SelectorUia | SelectorHtml | SelectorImage,
    preDelay: int = 300,
    postDelay: int = 200,
) -> int:

    selectorWindow = _extract_window_element(selector=selector)
    _, dictTarget = _UiElement.get_element_with_pre_delay(selector=selectorWindow, preDelay=preDelay)

    delay(postDelay)

    dictWindowAttr = cast(DictUiaSecondaryAttr, dictTarget)
    return int(dictWindowAttr["secondary-ProcessId"])


@Log.trace()
@lock_ui_operation
def get_window_pid(
    selector: SelectorWindow | SelectorUia | SelectorHtml | SelectorImage,
    timeout: int = 10000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> int:
    """
    Get the pid of the element's window.

    Parameters:
        selector: A selector dictionary generated by UI Analyzer for locating an element. You can edit it to make it more concise or more robust in different situations.
        timeout: Maximum time allowed for normal completion, in milliseconds. Values below 3000 are treated as 3000. The actual elapsed time may be longer if LiberRPA enters its hard-timeout fallback before raising a timeout-related exception.
        preDelay: Time to wait before performing the action, in milliseconds.
        postDelay: Time to wait after performing the action, in milliseconds.

    Returns:
        int: The pid of the window element.
    """

    timeout = _UiElement.check_set_timeout(timeout=timeout)

    return timeout_kill_thread(timeout=timeout)(_get_window_pid)(
        selector,
        preDelay,
        postDelay,
    )


def _get_window_file_path(
    selector: SelectorWindow | SelectorUia | SelectorHtml | SelectorImage,
    preDelay: int = 300,
    postDelay: int = 200,
) -> str:

    selectorWindow = _extract_window_element(selector=selector)
    _, dictTarget = _UiElement.get_element_with_pre_delay(selector=selectorWindow, preDelay=preDelay)

    delay(postDelay)

    dictWindowAttr = cast(DictUiaSecondaryAttr, dictTarget)
    return psutil.Process(int(dictWindowAttr["secondary-ProcessId"])).exe()


@Log.trace()
@lock_ui_operation
def get_window_file_path(
    selector: SelectorWindow | SelectorUia | SelectorHtml | SelectorImage,
    timeout: int = 10000,
    preDelay: int = 300,
    postDelay: int = 200,
) -> str:
    """
    Get the file path of the element's window.

    Parameters:
        selector: A selector dictionary generated by UI Analyzer for locating an element. You can edit it to make it more concise or more robust in different situations.
        timeout: Maximum time allowed for normal completion, in milliseconds. Values below 3000 are treated as 3000. The actual elapsed time may be longer if LiberRPA enters its hard-timeout fallback before raising a timeout-related exception.
        preDelay: Time to wait before performing the action, in milliseconds.
        postDelay: Time to wait after performing the action, in milliseconds.

    Returns:
        str: The file path string.
    """

    timeout = _UiElement.check_set_timeout(timeout=timeout)

    return timeout_kill_thread(timeout=timeout)(_get_window_file_path)(
        selector,
        preDelay,
        postDelay,
    )


if __name__ == "__main__":
    from time import monotonic

    # from liberrpa._Selector import *

    timeStart = monotonic()

    # close_window(selector=image1)
    print(
        check_window_exists(
            selector={
                "window": {
                    "ProcessName": "notepad.exe",
                    "FrameworkId": "Win32",
                    "ControlTypeName": "WindowControl",
                    "Name": "*New Text Document.txt - Notepad",
                    "ClassName": "Notepad",
                },
                "category": "uia",
                "specification": [{"ControlTypeName": "EditControl", "Name": "Text Editor", "ClassName": "Edit"}],
            }
        )
    )
    # print(get_active_window())
    # set_window_state(selector=image1, state="minimize")
    # print(get_window_position_and_size(selector=image1))
    # set_window_position(selector=image1, x=100, y=100)
    # set_window_size(selector=image1, width=500, height=500)

    # print(get_window_pid(selector=uiaWin2))
    # print(get_window_file_path(selector=image1))

    """ uiTarget, dictTarget = _UiElement.get_element(selector=image1)
    print(uiTarget)
    print(dictTarget) """
    """ pattern = uiTarget.GetPattern(uiautomation.PatternId.WindowPattern)
    print(pattern.WindowVisualState) """

    print("time used:", monotonic() - timeStart)
