name: default
channels:
  - conda-forge
dependencies:
  - pip
  - python=3.13
  - pymysql
  - websocket-client
  - pillow
  - pyqt-stubs
  - pystray
  - packaging
  - oracledb
  - flask-socketio
  - uiautomation
  - python-socketio
  - pymssql
  - xlwings
  - mail-parser
  - pynput
  - ftputil
  - ffmpeg
  - pymupdf
  - json5
  - pathvalidate
  - flask
  - python-mss
  - pandas
  - psutil
  - ruff
  - pywinhook
  - pypdf
  - ipykernel
  - pyperclip
  - pyautogui
  - yagmail
  - screeninfo
  - requests
  - pywin32
  - sqlalchemy
  - psycopg2
  - imapclient
  - keyboard
  - pyqt
  - python-engineio[version='>=4.13.4,<5']
  - libblas[build=*_openblas]
  - pip:
      - easyocr
      - pyzipper
