# FileName: _TransactionStorage.py
__author__ = "Jiyan Hu"
__email__ = "mailwork.hu@gmail.com"
__license__ = "GNU Affero General Public License v3.0 or later"
__copyright__ = f"Copyright (C) 2025 {__author__}"


from liberrpa.ComponentManagement.Common._Exception import ComponentManagementError
from liberrpa.ComponentManagement.Common._Validation import validate_uuid_v4
from liberrpa.ComponentManagement.Types._Warning import DictComponentManagementWarning

from hashlib import sha256
from pathlib import Path
import os
import shutil
from typing import Literal


_STR_STAGING_FOLDER_NAME = ".staging"


def get_repository_staging_folder_path(repositoryPath: Path) -> Path:
    return repositoryPath / _STR_STAGING_FOLDER_NAME


def validate_repository_transaction_folder_name(
    transactionFolderName: str,
    operationPrefix: Literal["publish", "import"],
) -> None:
    """Validate a Repository transaction folder name generated by LiberRPA."""
    strExpectedPrefix = f"{operationPrefix}_"
    if not transactionFolderName.startswith(strExpectedPrefix):
        raise ValueError(
            f"Repository transaction folder must start with {strExpectedPrefix!r}."
        )

    strTransactionId = transactionFolderName.removeprefix(strExpectedPrefix)
    validate_uuid_v4(strTransactionId, "Repository transaction ID")


def copy_wheel_to_staging(sourceWheelFilePath: Path, targetWheelFilePath: Path) -> str:
    """Copy a Wheel into staging and return the SHA-256 of the copied bytes."""
    hashObj = sha256()

    try:
        with (
            sourceWheelFilePath.open("rb") as sourceFileObj,
            targetWheelFilePath.open("xb") as targetFileObj,
        ):
            while bytesChunk := sourceFileObj.read(1024 * 1024):
                targetFileObj.write(bytesChunk)
                hashObj.update(bytesChunk)
            targetFileObj.flush()
            os.fsync(targetFileObj.fileno())
    except OSError as e:
        raise ComponentManagementError(
            code="io_error",
            message=(
                f"Failed to copy the Component Wheel into Repository staging: {targetWheelFilePath}"
            ),
        ) from e

    return hashObj.hexdigest()


def remove_repository_transaction_folder(
    transactionFolderPath: Path,
) -> DictComponentManagementWarning | None:
    try:
        shutil.rmtree(transactionFolderPath)
    except OSError as e:
        return {
            "code": "repository_cleanup_pending",
            "message": (
                "Repository transaction recovery completed, but temporary files could not be removed: "
                f"{transactionFolderPath}"
            ),
            "details": {
                "transactionFolderPath": str(transactionFolderPath),
                "reason": str(e),
            },
        }

    return None
